### ISSUE TITLE
想问问这个模式什么作用，是干嘛的？

### ISSUE THREAD

**Issue by Fate-Time** [hgjazhgj/hsiFotuAnihsneG#1]
[“config.json - 笨拙模式”](https://github.com/hgjazhgj/hsiFotuAnihsneG#%E5%8E%9F%E7%A5%9E%E6%99%BA%E8%83%BD%E9%92%93%E9%B1%BC)

文中“如果你觉得这个程序的表现太好了,首先来点一个star,然后可以考虑在config.json中打开笨拙模式开关”提到的‘笨拙模式("clumsyMode")’，不知是什么作用，设为 true 会怎样？

**Comment by hgjazhgj** [comment]
不知道就当作没用
