### ISSUE TITLE
您好 请教个问题

### ISSUE THREAD

**Issue by cyolc932** [hgjazhgj/hsiFotuAnihsneG#2]
我之前fork了这个被删除的仓库
然后我今天上线看github 发现他一直占用着 但没办法删除它
请问您是怎么解决这个问题的（问题指：删除这个![image](https://user-images.githubusercontent.com/46415893/162575904-75ddb87b-3d0d-477b-ac8f-d07f24ca21fd.png)

![image](https://user-images.githubusercontent.com/46415893/162575894-df825e5b-ca4d-4ba3-b6fd-50d920e1a0d3.png)
（我的仓库只有6个，因为这个变成7个）

**Comment by hgjazhgj** [comment]
这并非本项目涉及的内容,你不应该在此处发送此内容
