### ISSUE TITLE
2.4版本的钓鱼程序闪退，使用2.3版本钓鱼正常。

### ISSUE THREAD

**Issue by MTKmin** [hgjazhgj/hsiFotuAnihsneG#3]
下载最新版2.4钓鱼助手在无杀毒软件的情况下，打开原神调整分辨率到1920*1080，在管理员权限启动2.4钓鱼软件，发现打开闪退，退回到2.3版本后一切正常。

**Comment by hgjazhgj** [comment]
提供你的操作系统版本(在「设置-系统-关于-Windows规格-版本号」中查看)
如果程序在闪退前有输出,也请提供(在一个终端中运行而非双击启动程序)

**Comment by MTKmin** [comment]
版本	Windows 10 专业版
版本号	21H2
安装日期	‎2022/‎3/‎11
操作系统内部版本	19044.1766
体验	Windows Feature Experience Pack 120.2212.4180.0


![Images_1660412269039](https://user-images.githubusercontent.com/100497697/184504958-3f58617e-6aae-4f72-a379-c0004893c5db.GIF)

PS 开发者早点睡吧，还熬啊QAQ

**Comment by hgjazhgj** [comment]
在一个终端中运行而非双击启动程序
这样能看到完整的输出
你提供的gif中没有包含完整输出画面的帧

**Comment by hgjazhgj** [comment]
你需要先运行原神再运行本项目

**Comment by MTKmin** [comment]
2.4版本在打开原神的情况下运行，闪退情况复现。

**Comment by hgjazhgj** [comment]
所以闪退前到底输出了什么

**Comment by MTKmin** [comment]
百度在终端中运行python-指的是cmd窗口中运行
安装python环境 python下运行源代码 在github下载2.4源代码 python main.py
报错提示import cv2 出现错误 再次百度 使用pip install opencv-contrib-python安装 速度太慢
再次百度使用镜像安装 pip install -i https://pypi.tuna.tsinghua.edu.cn/simple opencv-contrib-python
安装完成后pywin32报错 同理pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pywin32安装
再次运行无问题可以正常使用 感谢您的回复
![001](https://user-images.githubusercontent.com/100497697/184529051-5ee0fc48-3f7f-4d58-a970-af5557e47670.jpg)
![002](https://user-images.githubusercontent.com/100497697/184529057-730dc86d-5cfd-4db6-8169-a551235bdb0d.jpg)

**Comment by aaahai00** [comment]
我也闪退，从新下不会闪退，但没有作用（不钓鱼，给管理员了）
退回2.3版本一切正常
系统规格：
版本	Windows 11 家庭中文版
版本	21H2
安装日期	‎2022/‎2/‎10
操作系统版本	22000.856
体验	Windows 功能体验包 1000.22000.856.0

**Comment by hgjazhgj** [comment]
关于这个问题，我计划像FGO-py一样做一个portable installer出来，彻底避免打包时出现的问题，同时方便后续更新

**Comment by hgjazhgj** [comment]
> 关于这个问题，我计划像FGO-py一样做一个portable installer出来，彻底避免打包时出现的问题，同时方便后续更新

Done
