### ISSUE TITLE
游戏3.2版本没有SMAA抗锯齿了...

### ISSUE THREAD

**Issue by hgjazhgj** [hgjazhgj/hsiFotuAnihsneG#4]
这导致无法识别上钩,以及亮色背景下游标定位可靠性下降
正在紧张刺激适配中

**Comment by hgjazhgj** [comment]
有一说一这个FSR本身是超分辨率算法，只不过第二代也有抗锯齿的效果
换而言之，只在渲染精度<1时有显著意义
这加了个新算法就把老的都噶了属实离谱

**Comment by YiFang172** [comment]
Traceback (most recent call last):   ]
  File "D:\Software\YuanShen\GenshinAutoFish\GenshinAutoFish\main.py", line 142, in main
    buf[front//10+2: back//10+5] = f' <{"":{back//10-front//10-1}}> '
ValueError: Sign not allowed in string format specifier
所以这个报错就是原神用FSR的原因吗

**Comment by hgjazhgj** [comment]
> Traceback (most recent call last): ] File "D:\Software\YuanShen\GenshinAutoFish\GenshinAutoFish\main.py", line 142, in main buf[front//10+2: back//10+5] = f' <{"":{back//10-front//10-1}}> ' ValueError: Sign not allowed in string format specifier 所以这个报错就是原神用FSR的原因吗

是的,由于没有透明度通道,现有的图像识别会受亮色背景的干扰,游标被定位到了不会出现的位置

**Comment by yyshana** [comment]
大佬啊，为什么打开后一直是wait？之前都可以的。

**Comment by hgjazhgj** [comment]
> 大佬啊，为什么打开后一直是wait？之前都可以的。

blocked

**Comment by hgjazhgj** [comment]
今天一看SMAA回来了
那没事了
有关注的知道是什么时候恢复的吗
